import { defineCollection, z } from 'astro:content';

const siteCollection = defineCollection({
  type: 'data',
  schema: z.object({
    brandName: z.string(),
    legalName: z.string(),
    description: z.string(),
    phone: z.string(),
    email: z.string().email(),
    social: z.record(z.string()),
    address: z.object({ line1: z.string(), line2: z.string() }),
    header: z.object({ primaryCtaLabel: z.string(), primaryCtaHref: z.string() }),
    footer: z.object({ exploreTitle: z.string(), contactTitle: z.string() }),
  }),
});

const navigationCollection = defineCollection({
  type: 'data',
  schema: z.array(z.object({ name: z.string(), href: z.string() })),
});

const pagesCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    layoutTitle: z.string(),
    layoutDescription: z.string().optional(),
    heroEyebrow: z.string().optional(),
    heroTitle: z.string().optional(),
    heroLead: z.string().optional(),
    heroMediaTitle: z.string().optional(),
    heroMediaText: z.string().optional(),
    ctaTitle: z.string().optional(),
    ctaDescription: z.string().optional(),
    ctaPrimaryLabel: z.string().optional(),
    ctaPrimaryHref: z.string().optional(),
    ctaSecondaryLabel: z.string().optional(),
    ctaSecondaryHref: z.string().optional(),
    routesTitle: z.string().optional(),
    routesLead: z.string().optional(),
    trustTitle: z.string().optional(),
    trustLead: z.string().optional(),
    scopeTitle: z.string().optional(),
    scopeLead: z.string().optional(),
    actionsTitle: z.string().optional(),
    actionsLead: z.string().optional(),
    overviewEyebrow: z.string().optional(),
    overviewTitle: z.string().optional(),
    overviewLead: z.string().optional(),
    registryEyebrow: z.string().optional(),
    registryTitle: z.string().optional(),
    customerFitEyebrow: z.string().optional(),
    customerFitTitle: z.string().optional(),
    relatedPathwayEyebrow: z.string().optional(),
    executiveSectionEyebrow: z.string().optional(),
    executiveSectionTitle: z.string().optional(),
    departmentSectionEyebrow: z.string().optional(),
    departmentSectionTitle: z.string().optional(),
    sectionQuickLinksTitle: z.string().optional(),
    sectionSystemTitle: z.string().optional(),
    sectionSystemEyebrow: z.string().optional(),
    fitTitle: z.string().optional(),
    fitLead: z.string().optional(),
    areasTitle: z.string().optional(),
    areasLead: z.string().optional(),
    signalsTitle: z.string().optional(),
    signalsLead: z.string().optional(),
    outputsTitle: z.string().optional(),
    outputsLead: z.string().optional(),
    connectionTitle: z.string().optional(),
    connectionLead: z.string().optional(),
    routingTitle: z.string().optional(),
    directoryTitle: z.string().optional(),
    headquartersTitle: z.string().optional(),
    sampleResourcesTitle: z.string().optional(),
  }),
});

const pageDataCollection = defineCollection({
  type: 'data',
  schema: z.object({
    routeCards: z.array(z.object({ title: z.string(), description: z.string(), href: z.string(), linkLabel: z.string(), icon: z.string() })).optional(),
    trustPoints: z.array(z.object({ title: z.string(), description: z.string() })).optional(),
    industries: z.array(z.string()).optional(),
    actionCards: z.array(z.object({ title: z.string(), description: z.string(), href: z.string(), label: z.string() })).optional(),
    executives: z.array(z.object({ name: z.string(), role: z.string(), vitals: z.string(), bio: z.string() })).optional(),
    departmentGroups: z.array(z.object({ department: z.string(), leads: z.array(z.object({ name: z.string(), role: z.string(), education: z.string(), expertise: z.string(), deepDive: z.string() })) })).optional(),
    orientation: z.object({ title: z.string(), description: z.string(), points: z.array(z.string()) }).optional(),
    serviceLines: z.array(z.object({ id: z.string(), title: z.string(), subtitle: z.string(), description: z.string(), icon: z.string(), services: z.array(z.string()) })).optional(),
    instrumentRegistry: z.array(z.object({ category: z.string(), tools: z.array(z.string()) })).optional(),
    serviceAssurance: z.array(z.object({ title: z.string(), description: z.string(), icon: z.string() })).optional(),
    customerFit: z.object({ title: z.string(), segments: z.array(z.string()) }).optional(),
    relatedPathway: z.object({ title: z.string(), description: z.string(), href: z.string(), label: z.string() }).optional(),
    supportAreas: z.array(z.object({ title: z.string(), description: z.string(), icon: z.string() })).optional(),
    lifecycleStages: z.array(z.string()).optional(),
    engagementModes: z.array(z.object({ title: z.string(), description: z.string() })).optional(),
    engagementSignals: z.array(z.object({ title: z.string(), description: z.string(), icon: z.string() })).optional(),
    supportOutputs: z.array(z.object({ title: z.string(), description: z.string() })).optional(),
    testingConnection: z.object({ summary: z.string(), steps: z.array(z.string()), primaryAction: z.object({ label: z.string(), href: z.string() }) }).optional(),
    qseDeepDive: z.array(z.object({ id: z.string(), title: z.string(), subtitle: z.string(), icon: z.string(), summary: z.string(), elements: z.array(z.object({ name: z.string(), implementation: z.string(), deepDive: z.string() })) })).optional(),
    pathways: z.array(z.object({ title: z.string(), description: z.string(), email: z.string().email(), serviceHref: z.string(), serviceLabel: z.string() })).optional(),
    routingSteps: z.array(z.object({ label: z.string(), text: z.string() })).optional(),
    headquarters: z.object({ addressLines: z.array(z.string()), mapUrl: z.string(), responseNote: z.string() }).optional(),
    sampleResources: z.array(z.object({ title: z.string(), description: z.string(), href: z.string(), label: z.string().optional() })).optional(),
    existingClients: z.object({ title: z.string(), description: z.string(), actions: z.array(z.object({ label: z.string(), detail: z.string().optional(), href: z.string() })) }).optional(),
  }),
});

export const collections = {
  site: siteCollection,
  navigation: navigationCollection,
  pages: pagesCollection,
  pageData: pageDataCollection,
};
